---
tooltip:
  trigger: item
  triggerOn: mousemove
series:
- type: tree
  data:
  - name: 故障现象1
    value: 10
    children:
    - name: 子系统A异常
      value: 30
      children:
      - name: 故障原因1
        value: 60
      - name: 故障原因2
        value: 40
    - name: 子系统B异常
      value: 50
      children:
      - name: 故障原因3
        value: 80
      - name: 故障原因4
        value: 20
      - name: 故障原因5
        value: 20
      - name: 故障原因6
        value: 20
    - name: 子系统C异常
      value: 30
      children:
      - name: 故障原因7
        value: 9
      - name: 故障原因8
        value: 11
      - name: 故障原因9
        value: 7
  top: 1%
  left: 20%
  bottom: 1%
  right: 20%
  symbolSize: 7
  label:
    position: left
    verticalAlign: middle
    align: right
    fontSize: 20
  leaves:
    label:
      position: right
      verticalAlign: middle
      align: left
  expandAndCollapse: true
  animationDuration: 550
  animationDurationUpdate: 750
