

icons:
  bz: mdi-human-male-male
  car: mdi-car-pickup
  device: mdi-network

items2:
- id: pb
  name: 炮兵
  catalog: bz
  kind: pb
  children:
  - id: pb_89a
    name: 89A
    catalog: dp
    kind: 89a
    children:
    - id: pb_89a_zsd89a
      name: ZSD89A
      catalog: car
      children:
      - id: x4
        name: 灭火系统
        children:
        - id: xx1
          catalog: device
          name: 灭火盒
        - id: xx2
          catalog: device
          name: 灭火瓶
        - id: xx3
          catalog: device
          name: 火警传感器
      - id: x5
        name: 三防系统
        children:
        - 
      - id: x6
        name: 烟幕弹/榴霰弹控制系统
        children:
        - 
     