
# debug: true
autorun: demo4
layout:
    - {x: 0, y: 0, w: 12, h: 36, i: "chart1"}
chart1:
    type: e-xy-chart
    option:
        maxCount: 2000
        redrawTime: 120
        xAxis:
            type: value
            min: 140
            max: 190
        yAxis:
            type: value
            max: 120
        title:
            text: 散点图
            left: center
        series:
        -   name: 模拟数据
            type: scatter
            encode:
                x: v1
                y: v2
