- id: 1
  name: 测试项1
  memo: 对设备部件A的xxx1功能进行测试
  icon: mdi-comment-check-outline
- id: 2
  name: 测试项2
  memo: 对设备的xxx2功能进行测试
  icon: mdi-comment-check-outline
- id: 3
  name: 测试项3
  memo: 对设备的xxx3功能和xxxx功能进行测试
  icon: mdi-shield-check-outline
- id: 4
  name: 测试项4
  memo: 对设备的xxx4功能进行测试
  icon: mdi-shield-check-outline
- id: 5
  name: 测试项5
  memo: 对设备的xxx5功能的性能测试
  icon: mdi-clock-check-outline
- id: 6
  name: 测试项6
  memo: 对设备xxx子系统的xxx6功能进行测试
  icon: mdi-clock-check-outline